### PR TITLE
Deactivate SCIM by default

### PR DESCRIPTION
**Pull request by msiegenthaler**
This PR deactivates SCIM on new realms by default and prevents that SCIM is automatically active on all realm after installing the extension.
This ensures that the administrator doesn't activate SCIM by accident, since it might be "invisible" when the admin theme is not changed.

### CODE REVIEW

**Comment by msiegenthaler** [comment]
argh, sorry, need to rebase :)

**Comment by Captain-P-Goldfish** [comment]
An additiional note in the README.MD would be great that mentions that the endpoints are disabled by default

**Comment by msiegenthaler** [comment]
added a note

**Comment by Captain-P-Goldfish** [comment]
Just checked and found one little problem. See screen.

If an admin creates a new realm and SCIM is disabled the endpoints are not accessed and thus the resource-types are not created in the database. So when pressing the resource-types tab we get a "Resource Not Found" page.

screen

**Comment by Captain-P-Goldfish** [comment]
But I guess this is actually my own error isn't it? :-)

**Comment by Captain-P-Goldfish** [comment]
Hi do you still plan to fix the integration-tests on this?

**Comment by msiegenthaler** [comment]
Jup, just got „delayed“ by the patch of good weather lately 😀

**Pull request merged**
